{{- if .Values.httpRoute }}
{{- if .Values.httpRoute.preview }}
{{- if .Values.httpRoute.preview.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "common-application-charts.fullname" . }}-preview-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common-application-charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview
  {{- with .Values.httpRoute.preview.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.httpRoute.gatewayName | default (printf "%s-gateway" (include "common-application-charts.fullname" .)) }}
    {{- if .Values.httpRoute.gatewayNamespace }}
    namespace: {{ .Values.httpRoute.gatewayNamespace }}
    {{- end }}
    {{- if .Values.httpRoute.preview.sectionName }}
    sectionName: {{ .Values.httpRoute.preview.sectionName }}
    {{- end }}
  {{- if .Values.httpRoute.preview.hostnames }}
  hostnames:
  {{- range .Values.httpRoute.preview.hostnames }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.preview.rules }}
  - matches:
    {{- range .matches }}
    - path:
        type: {{ .path.type | default "PathPrefix" }}
        value: {{ .path.value | default "/" }}
      {{- if .headers }}
      headers:
      {{- range .headers }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
    {{- end }}
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name | default (printf "%s-preview" $.Release.Name) }}
      port: {{ .port }}
      {{- if .weight }}
      weight: {{ .weight }}
      {{- end }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    {{- end }}
    {{- if .filters }}
    filters:
    {{- range .filters }}
    - type: {{ .type }}
      {{- if eq .type "RequestHeaderModifier" }}
      requestHeaderModifier:
        {{- if .requestHeaderModifier.set }}
        set:
        {{- range .requestHeaderModifier.set }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        {{- end }}
        {{- if .requestHeaderModifier.add }}
        add:
        {{- range .requestHeaderModifier.add }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        {{- end }}
        {{- if .requestHeaderModifier.remove }}
        remove:
        {{- range .requestHeaderModifier.remove }}
        - {{ . }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}
