replicaCount: 2

image:
  repository: registry.digitalocean.com/home-lab-container-registry/mt-doctor-record-service
  tag: d894880

environment: dev

service:
  type: ClusterIP
  port: 8084
  targetPort: 8084

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

ingress:
  className: kong
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "dev.doctor-records.apps.meditrack-app.me"
      paths:
        - "/"
  tls:
    - hosts:
        - "dev.doctor-records.apps.meditrack-app.me"
        - "preview.dev.doctor-records.apps.meditrack-app.me"
      secretName: "dev-doctor-records-tls-secret"

podAnnotations:
  secret.reloader.stakater.com/reload: "db-credentials"

strategy:
  type: blueGreen
  blueGreen:
    activeService: "dev-doctor-records"
    previewService: "preview-dev-doctor-records"
    autoPromotionEnabled: true

# strategy:
#   type: canary
#   canary:
#     maxSurge: 25%
#     maxUnavailable: 0
#     steps:
#       - setWeight: 10
#       - pause:
#           duration: 30s
#       - setWeight: 30
#       - pause:
#           duration: 30s
#       - setWeight: 60
#       - pause:
#           duration: 30s
#       - setWeight: 100

envFromSecrets:
  DB_USER:
    secretName: db-credentials
    key: username
  DB_PASSWORD:
    secretName: db-credentials
    key: password
  DB_NAME:
    secretName: db-credentials
    key: name
  DB_HOST:
    secretName: db-credentials
    key: host
  DB_PORT:
    secretName: db-credentials
    key: port
