replicaCount: 2

image:
  repository: registry.digitalocean.com/home-lab-container-registry/mt-doctor-record-service
  tag: d894880

environment: dev

service:
  type: ClusterIP
  port: 8084
  targetPort: 8084

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

ingress:
  enabled: true  # Add explicit enabled flag
  className: kong
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "dev.doctor-records.apps.meditrack-app.me"
      paths:
        - "/"
  tls:
    - hosts:
        - "dev.doctor-records.apps.meditrack-app.me"
        - "preview.dev.doctor-records.apps.meditrack-app.me"
      secretName: "dev-doctor-records-tls-secret"

# Gateway API Configuration (alternative to ingress)
gateway:
  enabled: false  # Set to true to use Gateway API instead of Ingress
  gatewayClassName: "kong"
  annotations: {}
  listeners:
    - name: "http"
      port: 80
      protocol: "HTTP"
      hostname: "dev.doctor-records.apps.meditrack-app.me"
    - name: "https"
      port: 443
      protocol: "HTTPS"
      hostname: "dev.doctor-records.apps.meditrack-app.me"
      tls:
        mode: "Terminate"
        certificateRefs:
          - name: "dev-doctor-records-tls-secret"


httpRoute:
  enabled: false  # Set to true to use HTTPRoute instead of Ingress
  gatewayName: ""  # Will default to {release-name}-gateway
  gatewayNamespace: ""  # Optional, defaults to same namespace
  hostnames:
    - "dev.doctor-records.apps.meditrack-app.me"
  rules:
    - matches:
        - path:
            type: "PathPrefix"
            value: "/"
      backendRefs:
        - name: ""  # Will default to service name
          port: 8084
          weight: 100
      filters:
        - type: "RequestHeaderModifier"
          requestHeaderModifier:
            add:
              - name: "X-Gateway-API"
                value: "kong"

podAnnotations:
  secret.reloader.stakater.com/reload: "db-credentials"

strategy:
  type: blueGreen
  blueGreen:
    activeService: "dev-doctor-records"
    previewService: "preview-dev-doctor-records"
    autoPromotionEnabled: true

# strategy:
#   type: canary
#   canary:
#     maxSurge: 25%
#     maxUnavailable: 0
#     steps:
#       - setWeight: 10
#       - pause:
#           duration: 30s
#       - setWeight: 30
#       - pause:
#           duration: 30s
#       - setWeight: 60
#       - pause:
#           duration: 30s
#       - setWeight: 100

envFromSecrets:
  DB_USER:
    secretName: db-credentials
    key: username
  DB_PASSWORD:
    secretName: db-credentials
    key: password
  DB_NAME:
    secretName: db-credentials
    key: name
  DB_HOST:
    secretName: db-credentials
    key: host
  DB_PORT:
    secretName: db-credentials
    key: port
