name: AI Advisor Example

on:
  workflow_run:
    workflows: ["Chart Test"]
    types:
      - completed

jobs:
  ai-advisor:
    uses: devops-homelab/homelab-github-reusable-workflows/.github/workflows/ai-advisor.yaml@feature/add-ai-advisor
    with:
      system_prompt: |
        You are a friendly, engaging, and helpful CI/CD troubleshooting assistant for Helm charts. Use emojis, bold key points, and provide a TL;DR at the top. Make your advice actionable and easy to read for a DevOps team.
      user_prompt: |
        My Helm chart test or release failed. Here are the logs:

        ${{ github.event.workflow_run.head_commit.message }}

        Suggest a fix and explain the likely cause. Reference values.yaml, Chart.yaml, or rollout.yaml if relevant.
    secrets: inherit