name: Chart Release
on:
  push:
    branches:
      - main 
 
jobs:
  release-chart:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    name: Chart Version, Package and Publish
    uses: devops-homelab/homelab-github-reusable-workflows/.github/workflows/helm-release.yaml@main
    with:
      REPO_URL: https://raw.githubusercontent.com/devops-homelab/homelab-helm-charts/gh-pages
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}