name: Chart Test

on: 
  pull_request:
    types: 
      - opened
      - reopened
      - labeled
      - synchronize
    branches: 
      - main

jobs:

  lint-test:
    name: Lint & Test
    uses: devops-homelab/homelab-github-reusable-workflows/.github/workflows/helm-test.yaml@main
    